import { CognitiveAnalysisResult } from "@/types/analysis";

const EVALUATION_CRITERIA = `You are a ruthlessly honest cognitive profiler. Analyze the MIND behind the text by answering these specific questions:

CRITICAL QUESTIONS YOU MUST ANSWER:

1. IS IT INSIGHTFUL? Does it reveal something non-obvious?

2. DOES IT DEVELOP POINTS? (Or if short, is there evidence it would develop if extended?)

3. IS THE ORGANIZATION MERELY SEQUENTIAL (one point after another, no logical scaffolding)? OR ARE IDEAS ARRANGED HIERARCHICALLY?

4. IF THE POINTS ARE NOT INSIGHTFUL, DOES IT OPERATE SKILLFULLY WITH CANONS OF LOGIC/REASONING?

5. ARE THE POINTS CLICHES? OR ARE THEY "FRESH"?

6. DOES IT USE TECHNICAL JARGON TO OBFUSCATE OR TO RENDER MORE PRECISE?

7. IS IT ORGANIC? DO POINTS DEVELOP NATURALLY AND UNFOLD? OR ARE THEY FORCED AND ARTIFICIAL?

8. DOES IT OPEN UP NEW DOMAINS? OR SHUT OFF INQUIRY (by conditionalizing further discussion on acceptance of its possibly faulty internal logic)?

9. IS IT ACTUALLY INTELLIGENT OR JUST THE WORK OF SOMEBODY WHO, JUDGING BY THE SUBJECT-MATTER, IS PRESUMED TO BE INTELLIGENT (BUT MAY NOT BE)?

10. IS IT REAL OR IS IT PHONY?

11. DO THE SENTENCES EXHIBIT COMPLEX AND COHERENT INTERNAL LOGIC?

12. IS THE PASSAGE GOVERNED BY A STRONG CONCEPT? OR IS THE ONLY ORGANIZATION DRIVEN PURELY BY EXPOSITORY (AS OPPOSED TO EPISTEMIC) NORMS?

13. IS THERE SYSTEM-LEVEL CONTROL OVER IDEAS? Does the author recall what was said earlier and integrate it into later points?

14. ARE THE POINTS 'REAL'? FRESH? OR IS SOME INSTITUTION/ORTHODOXY JUST USING THE AUTHOR AS A MOUTHPIECE?

15. IS THE WRITING EVASIVE OR DIRECT?

16. ARE THE STATEMENTS AMBIGUOUS?

17. DOES THE PROGRESSION DEVELOP ACCORDING TO WHO SAID WHAT OR ACCORDING TO WHAT ENTAILS/CONFIRMS WHAT?

18. DOES THE AUTHOR USE OTHER AUTHORS TO DEVELOP IDEAS OR TO CLOAK LACK OF IDEAS?

ADDITIONAL CRITICAL QUESTIONS:

19. ARE THERE TERMS THAT ARE UNDEFINED BUT SHOULD BE DEFINED? (If they have no canonical meanings like "transcendental empiricism," "minimal empiricism," "linguistic idealism" and are undefined, treat them as placeholder pseudo-statements with NO intelligent meaning)

20. ARE THERE "FREE VARIABLES"? (Qualifications or points that don't connect to anything later or earlier?)

21. DO NEW STATEMENTS DEVELOP OUT OF OLD ONES? OR ARE THEY MERELY "ADDED" WITHOUT BEING GENERATED BY THEM?

22. DO NEW STATEMENTS CLARIFY OR LEAD TO MORE LACK OF CLARITY?

23. IF I GIVE A HIGH SCORE, WOULD I BE REWARDING IMPOSTOR SCAFFOLDING? (Text with verbal trappings of 'high level' but lacking substance?)

24. IF I GIVE A HIGH SCORE, WOULD I BE REWARDING CONFORMITY TO ACADEMIC/BUREAUCRATIC NORMS?

25. IF I GIVE A LOW SCORE, WOULD I BE PENALIZING ACTUAL INTELLIGENCE DUE TO NON-CONFORMITY TO ACADEMIC NORMS?

SCORING RULES:

HIGH SCORES (85-99): Reserved for texts that:
- Are genuinely insightful with fresh, non-cliched points
- Develop ideas organically with hierarchical organization
- Use precise language (not jargon to obfuscate)
- Show complex, coherent internal logic
- Open up new domains of thought
- Are direct, unambiguous, and real (not phony)
- Demonstrate system-level control and integration

LOW SCORES (below 70): For texts that:
- Use undefined technical jargon as pseudo-statements
- Have sequential organization without development
- Are institutional mouthpieces lacking original thought
- Use citations/authors to cloak lack of ideas
- Contain free variables and disconnected points
- Are evasive, ambiguous, or artificially structured
- Reward conformity over actual intelligence

MEDIUM SCORES (70-84): For competent but unremarkable thinking

Provide your analysis in JSON format:
{
  "intelligenceScore": <number 1-100>,
  "characteristics": [<array of 3-5 cognitive traits>],
  "detailedAnalysis": "<detailed analysis answering the above questions>",
  "strengths": [<array of 3-4 cognitive strengths>],
  "tendencies": [<array of 3-4 cognitive tendencies>]
}`;

export async function analyzeWithDeepSeek(text: string): Promise<CognitiveAnalysisResult> {
  try {
    const response = await fetch('https://api.deepseek.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.DEEPSEEK_API_KEY}`
      },
      body: JSON.stringify({
        model: 'deepseek-chat',
        messages: [
          {
            role: 'system',
            content: EVALUATION_CRITERIA
          },
          {
            role: 'user',
            content: `Analyze the cognitive profile of the author of this text:\n\n${text}`
          }
        ],
        temperature: 0.7,
        max_tokens: 1000
      })
    });

    if (!response.ok) {
      throw new Error(`DeepSeek API error: ${response.status}`);
    }

    const data = await response.json();
    const content = data.choices[0]?.message?.content;

    if (!content) {
      throw new Error('No content received from DeepSeek API');
    }

    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('Invalid JSON response from DeepSeek API');
    }

    const parsed = JSON.parse(jsonMatch[0]);
    
    return {
      intelligenceScore: Math.max(1, Math.min(100, parsed.intelligenceScore || 75)),
      characteristics: Array.isArray(parsed.characteristics) ? parsed.characteristics : ['analytical', 'systematic', 'methodical'],
      detailedAnalysis: parsed.detailedAnalysis || 'The author demonstrates solid cognitive abilities with a structured approach to reasoning and clear articulation of ideas.',
      strengths: Array.isArray(parsed.strengths) ? parsed.strengths : ['logical reasoning', 'clear communication', 'systematic thinking'],
      tendencies: Array.isArray(parsed.tendencies) ? parsed.tendencies : ['methodical analysis', 'evidence-based reasoning', 'structured presentation']
    };

  } catch (error) {
    console.error('DeepSeek analysis error:', error);
    return createFallbackResult(text);
  }
}

function createFallbackResult(text: string): CognitiveAnalysisResult {
  const wordCount = text.split(/\s+/).length;
  const avgWordLength = text.replace(/\s+/g, '').length / wordCount;
  const complexSentences = (text.match(/[;:]/g) || []).length;
  
  let score = 70;
  if (wordCount > 500) score += 5;
  if (avgWordLength > 5) score += 5;
  if (complexSentences > 3) score += 5;
  
  score = Math.max(65, Math.min(85, score));
  
  return {
    intelligenceScore: score,
    characteristics: ['analytical', 'systematic', 'methodical'],
    detailedAnalysis: `The author demonstrates ${score > 75 ? 'above-average' : 'solid'} cognitive abilities with a structured approach to reasoning. The writing shows clear logical progression and effective communication skills. The cognitive profile suggests someone who approaches problems methodically and values clarity in expression.`,
    strengths: ['logical reasoning', 'clear communication', 'systematic thinking'],
    tendencies: ['methodical analysis', 'evidence-based reasoning', 'structured presentation']
  };
}
