import OpenAI from "openai";
import { CognitiveAnalysisResult } from "@/types/analysis";

const openai = new OpenAI({ 
  apiKey: process.env.OPENAI_API_KEY || "missing_api_key"
});

const EVALUATION_CRITERIA = `You are a ruthlessly honest cognitive profiler. Analyze the MIND behind the text by answering these specific questions:

CRITICAL QUESTIONS YOU MUST ANSWER:

1. IS IT INSIGHTFUL? Does it reveal something non-obvious?

2. DOES IT DEVELOP POINTS? (Or if short, is there evidence it would develop if extended?)

3. IS THE ORGANIZATION MERELY SEQUENTIAL (one point after another, no logical scaffolding)? OR ARE IDEAS ARRANGED HIERARCHICALLY?

4. IF THE POINTS ARE NOT INSIGHTFUL, DOES IT OPERATE SKILLFULLY WITH CANONS OF LOGIC/REASONING?

5. ARE THE POINTS CLICHES? OR ARE THEY "FRESH"?

6. DOES IT USE TECHNICAL JARGON TO OBFUSCATE OR TO RENDER MORE PRECISE?

7. IS IT ORGANIC? DO POINTS DEVELOP NATURALLY AND UNFOLD? OR ARE THEY FORCED AND ARTIFICIAL?

8. DOES IT OPEN UP NEW DOMAINS? OR SHUT OFF INQUIRY (by conditionalizing further discussion on acceptance of its possibly faulty internal logic)?

9. IS IT ACTUALLY INTELLIGENT OR JUST THE WORK OF SOMEBODY WHO, JUDGING BY THE SUBJECT-MATTER, IS PRESUMED TO BE INTELLIGENT (BUT MAY NOT BE)?

10. IS IT REAL OR IS IT PHONY?

11. DO THE SENTENCES EXHIBIT COMPLEX AND COHERENT INTERNAL LOGIC?

12. IS THE PASSAGE GOVERNED BY A STRONG CONCEPT? OR IS THE ONLY ORGANIZATION DRIVEN PURELY BY EXPOSITORY (AS OPPOSED TO EPISTEMIC) NORMS?

13. IS THERE SYSTEM-LEVEL CONTROL OVER IDEAS? Does the author recall what was said earlier and integrate it into later points?

14. ARE THE POINTS 'REAL'? FRESH? OR IS SOME INSTITUTION/ORTHODOXY JUST USING THE AUTHOR AS A MOUTHPIECE?

15. IS THE WRITING EVASIVE OR DIRECT?

16. ARE THE STATEMENTS AMBIGUOUS?

17. DOES THE PROGRESSION DEVELOP ACCORDING TO WHO SAID WHAT OR ACCORDING TO WHAT ENTAILS/CONFIRMS WHAT?

18. DOES THE AUTHOR USE OTHER AUTHORS TO DEVELOP IDEAS OR TO CLOAK LACK OF IDEAS?

ADDITIONAL CRITICAL QUESTIONS:

19. ARE THERE TERMS THAT ARE UNDEFINED BUT SHOULD BE DEFINED? (If they have no canonical meanings like "transcendental empiricism," "minimal empiricism," "linguistic idealism" and are undefined, treat them as placeholder pseudo-statements with NO intelligent meaning)

20. ARE THERE "FREE VARIABLES"? (Qualifications or points that don't connect to anything later or earlier?)

21. DO NEW STATEMENTS DEVELOP OUT OF OLD ONES? OR ARE THEY MERELY "ADDED" WITHOUT BEING GENERATED BY THEM?

22. DO NEW STATEMENTS CLARIFY OR LEAD TO MORE LACK OF CLARITY?

23. IF I GIVE A HIGH SCORE, WOULD I BE REWARDING IMPOSTOR SCAFFOLDING? (Text with verbal trappings of 'high level' but lacking substance?)

24. IF I GIVE A HIGH SCORE, WOULD I BE REWARDING CONFORMITY TO ACADEMIC/BUREAUCRATIC NORMS?

25. IF I GIVE A LOW SCORE, WOULD I BE PENALIZING ACTUAL INTELLIGENCE DUE TO NON-CONFORMITY TO ACADEMIC NORMS?

SCORING RULES:

HIGH SCORES (85-99): Reserved for texts that:
- Are genuinely insightful with fresh, non-cliched points
- Develop ideas organically with hierarchical organization
- Use precise language (not jargon to obfuscate)
- Show complex, coherent internal logic
- Open up new domains of thought
- Are direct, unambiguous, and real (not phony)
- Demonstrate system-level control and integration

LOW SCORES (below 70): For texts that:
- Use undefined technical jargon as pseudo-statements
- Have sequential organization without development
- Are institutional mouthpieces lacking original thought
- Use citations/authors to cloak lack of ideas
- Contain free variables and disconnected points
- Are evasive, ambiguous, or artificially structured
- Reward conformity over actual intelligence

MEDIUM SCORES (70-84): For competent but unremarkable thinking

Your response must be in JSON format:
{
  "intelligenceScore": <number between 1-100>,
  "characteristics": [<string>, <string>, ...],
  "detailedAnalysis": <string addressing the evaluation questions>,
  "strengths": [<string>, <string>, ...],
  "tendencies": [<string>, <string>, ...]
}`;

export async function analyzeWithOpenAI(text: string): Promise<CognitiveAnalysisResult> {
  try {
    if (!process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === "missing_api_key") {
      throw new Error("OpenAI API key is missing. Please set the OPENAI_API_KEY environment variable.");
    }

    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { 
          role: "system", 
          content: EVALUATION_CRITERIA
        },
        { 
          role: "user", 
          content: text 
        }
      ],
      response_format: { type: "json_object" },
      temperature: 0.7
    });

    const content = response.choices[0].message.content;
    
    if (!content) {
      throw new Error("No response from OpenAI API");
    }

    const result = JSON.parse(content) as CognitiveAnalysisResult;
    
    if (
      typeof result.intelligenceScore !== 'number' ||
      !Array.isArray(result.characteristics) ||
      typeof result.detailedAnalysis !== 'string' ||
      !Array.isArray(result.strengths) ||
      !Array.isArray(result.tendencies)
    ) {
      throw new Error("Invalid response format from OpenAI API");
    }

    return result;
  } catch (error) {
    console.error("Error in OpenAI API call:", error);
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    throw new Error("Failed to analyze text with OpenAI: " + errorMessage);
  }
}
